### PR TITLE
Add github actions workflow files, docker compose files and Dockerfile

### PR DESCRIPTION
**Pull request by maexled**
Part of Gamify-IT/issues#480

### CODE REVIEW

**Comment by maexled** [comment]
Merge after #5

**Review by madebyTimo — APPROVED** [review]
Github action files, docker compose files, nginx files and Dockerfile look fine.

The Sonarqube workflow file is missing. Should it also be added in this PR?

**Comment by maexled** [comment]
> The Sonarqube workflow file is missing. Should it also be added in this PR?

It is alread in the main branch.

**Comment by madebyTimo** [comment]
I just saw that the `MEMORY_URL` is missing for the overworld-backend in the `docker-compose-dev` file. I will add it

**Comment by maexled** [comment]
Since testCloneConfiguration already fails in main, I will merge the pr despite failed github action

**Pull request merged**
